homepage: "https://github.com/coreos/ignition"
main_repo: "https://github.com/coreos/ignition"
primary_contact: "coreos-infra@lists.fedoraproject.org"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
