homepage: "https://github.com/coreos/ignition"
homepage: "https://github.com/coreos/ignition"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
