homepage: "https://github.com/attic-labs/noms"
main_repo: "https://github.com/attic-labs/noms"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
