homepage: "https://grafana.com"
main_repo: "https://github.com/grafana/grafana"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
