homepage: "https://github.com/igraph/igraph"
main_repo: "https://github.com/igraph/igraph"
language: c
primary_contact: "szhorvat@gmail.com"
auto_ccs:
  - "Adam@adalogics.com"
sanitizers:
  - address
  - undefined
