homepage: "https://godoc.org/inet.af/netaddr"
main_repo: "https://github.com/inetaf/netaddr"
primary_contact: ""
auto_ccs :
  - "Adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
