homepage: "https://github.com/filecoin-project/lotus"
main_repo: "https://github.com/filecoin-project/lotus"
primary_contact: ""
auto_ccs :
  - "Adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
