homepage: "https://github.com/tristanpenman/valijson"
main_repo: "https://github.com/tristanpenman/valijson"
language: c++
primary_contact: ""
auto_ccs:
  - "Adam@adalogics.com"
sanitizers:
  - address
  - undefined
  - memory
