homepage: "https://opentelemetry.io/"
language: go
primary_contact: ""
main_repo: "https://github.com/open-telemetry/community"
auto_ccs:
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
