homepage: "https://github.com/redis/hiredis"
primary_contact: ""
language: c
fuzzing_engines:
  - libfuzzer
  - honggfuzz
auto_ccs:
  - "Adam@adalogics.com"
main_repo: "https://github.com/redis/hiredis"
