homepage: "https://www.jaegertracing.io"
main_repo: "https://github.com/jaegertracing/jaeger"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
