homepage: "https://github.com/proftpd/proftpd"
main_repo: "https://github.com/proftpd/proftpd"
language: c
primary_contact: ""
auto_ccs:
  - "Adam@adalogics.com"
sanitizers:
  - address
  - undefined
  - memory
