homepage: "https://github.com/saltstack/salt"
main_repo: "https://github.com/saltstack/salt"
language: python
primary_contact: ""
auto_ccs:
 - "Adam@adalogics.com"
sanitizers:
 - address
 - undefined
architectures:
 - x86_64
fuzzing_engines:
  - libfuzzer
