homepage: "https://github.com/opencontainers/umoci"
main_repo: "https://github.com/opencontainers/umoci"
primary_contact: "Adam@adalogics.com"
auto_ccs:
  - "cyphar@cyphar.com"
  - "tycho@tycho.pizza"
  - "vbatts@hashbangbash.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
