homepage: "https://github.com/pilosa/pilosa"
main_repo: "https://github.com/pilosa/pilosa"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
