homepage: "https://github.com/home-assistant/core"
main_repo: "https://github.com/home-assistant/core"
language: python
primary_contact: ""
auto_ccs:
 - "Adam@adalogics.com"
sanitizers:
 - address
 - undefined
architectures:
 - x86_64
fuzzing_engines:
  - libfuzzer
