homepage: "https://thanos.io"
main_repo: "https://github.com/thanos-io/thanos"
primary_contact: ""
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
