homepage: "https://github.com/videolan/vlc"
language: c
primary_contact: ""
auto_ccs:
  - "Adam@adalogics.com"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/videolan/vlc'
